name: .NET Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: windows-latest

    env:
      Solution_Name: CyberSecurity_Awarenessbot.sln

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x # Adjust to your project's .NET version

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Validate Solution File
        run: |
          if (-not (Test-Path -Path "${{ env.Solution_Name }}")) {
            Write-Error "❌ Solution file not found!"
            exit 1
          }
        shell: pwsh

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run All Unit Tests
        run: |
          Get-ChildItem -Path . -Recurse -Filter "*.Tests.csproj" | ForEach-Object {
            dotnet test $_.FullName --configuration Debug --no-restore
          }
        shell: pwsh
